name: tfsec

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # pin@v1.0.3
        with:
          working_directory: terraform/
